### ISSUE TITLE
[GSoC 2024] xtable API for luanetfilter

### ISSUE THREAD

**Issue by sheharyaar** [luainkernel/lunatik#107]
Issue to track xtable APIs and features for luanetfilter module.
Design issue : #105

**Comment by sheharyaar** [comment]
Deliverables checkilst :
- [ ] xtables registration with the kernel
- [ ] userspace library generation and adding API functions for the userspace library
- [ ] adding skbuff helpers for interaction with the packet (porting luapacket)
- [ ] adding helpers for xtable `match/target` params, `mtchk/tgchk` params, `mtdtor/tgdtor` params for xtable callbacks

**Comment by jperon** [comment]
Hello,
following this issue with much interest, I was wondering what would be the nftables equivalent of following command (from Readme.md about dnsblock):

```sh
sudo iptables -A OUTPUT -m dnsblock -j DROP
```

Thank you very much for the hard work!

**Comment by sheharyaar** [comment]
Hi, thanks for the compliment. I am currently working on nftable implementation or the same. I will update here once that is done :)

**Comment by jperon** [comment]
Many thanks for your quick reply; can’t wait for the update!

**Comment by jperon** [comment]
Not sure it’s the right place for questions, but I had the following one: does the `skb` argument of `match` function passed to `xtable.match` contain the whole ip packet, or only the header part?

**Comment by sheharyaar** [comment]
The whole packet starting from the ip header.

**Comment by sheharyaar** [comment]
In the `examples/dnsblock/dnsblock.lua`, we extract the dns name because the skb includes the entire packet (https://github.com/luainkernel/lunatik/blob/master/examples/dnsblock/dnsblock.lua#L51). In this case `thoff` is the transport header offset (ipv4 header offsert) and the dns (udp data) is 20 bytes from the thoff.

**Comment by jperon** [comment]
Thanks again for the reply. My question came because, trying to develop a SNI filter like https://github.com/luainkernel/lunatik/blob/master/examples/filter/sni.lua, but using `xtables` instead of `xdp`, I always get `#skt == 52` with this rule: `iptables  -A OUTPUT -p tcp --dport 443 -m sni -j REJECT`, event when the `Total length` of the ip packet (obtained with `short(2)`) is bigger. And in fact, if I try `skt:getbyte(53)`, I get this error in kernel logs: `luaxtable: match error: bad argument #2 to '?' (out of bounds)`.

**Comment by lneto** [comment]
> Thanks again for the reply. My question came because, trying to develop a SNI filter like https://github.com/luainkernel/lunatik/blob/master/examples/filter/sni.lua, but using `xtables` instead of `xdp`, I always get `#skt == 52` with this rule: `iptables -A OUTPUT -p tcp --dport 443 -m sni -j REJECT`, event when the `Total length` of the ip packet (obtained with `short(2)`) is bigger. And in fact, if I try `skt:getbyte(53)`, I get this error in kernel logs: `luaxtable: match error: bad argument #2 to '?' (out of bounds)`.

I think you are probably using the wrong offset.. if I'm not mistaken, luaxtable's skb starts from IP header and luaxdp's starts from ETH header; also, the payload offset is computed in [the eBPF program](https://github.com/luainkernel/lunatik/blob/9dd084c2559b4aa01bdb0b7d7be1e11fc49098bd/examples/filter/https.c#L43).

Can you share the actual script? I could give you some hint.. feel welcome to join us on Matrix as well..

**Comment by jperon** [comment]
Following my initial question, is there an `ebtables` equivalent of `sudo iptables -A OUTPUT -m dnsblock -j DROP` (to filter traffic between bridged interfaces), or will I have to wait for the nftables implementation?

**Comment by sheharyaar** [comment]
Yes. It's there in the PR (#154 ), the following fields : https://github.com/luainkernel/lunatik/pull/154/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R1222


But it would be a great help if you can test it out on your own convenience :)

**Comment by jperon** [comment]
Thank you, but if I understand well, it’s not the same logic as with `iptables` and `dnsblock.lua`: instead of an `ebtables` command, I should use `netfilter.register`, isn’t it? Is there anywhere an example of such a use case, please?

**Comment by sheharyaar** [comment]
I guess you can use `ebtables`, and use `iptables` example only. You can `netfilter.family` of type NF_BRIDGE I guess. I haven't tried it yet.

**Comment by jperon** [comment]
> But it would be a great help if you can test it out on your own convenience :)

[Here is](https://github.com/jperon/lunatik_snihook) the initial version of a sni filter implemented with netfilter API.

I really don’t know how to thank for such a great tool: I thought having the ability to script a whole firewall in MoonScript would remain a foolish dream forever!

**Comment by sheharyaar** [comment]
It's a pleasure to hear this.

**Comment by sheharyaar** [comment]
Can be closed as completed.
