### ISSUE TITLE
[ARM] Compilation error

### ISSUE THREAD

**Issue by jperon** [luainkernel/lunatik#157]
While compiling on ARM (Debian, kernel 6.1.0-21), it returns following error:

```
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-21-arm64'
  CC [M]  /opt/lunatik/lib/luasocket.o
/opt/lunatik/lib/luasocket.c: In function ‘luasocket_pushaddr’:
/opt/lunatik/lib/luasocket.c:47:40: error: invalid application of ‘sizeof’ to incomplete type ‘char[]’
   47 | #define LUASOCKET_ADDRMIN(addr) (sizeof((addr)->sa_data))
      |                                        ^
/opt/lunatik/lib/luasocket.c:89:47: note: in expansion of macro ‘LUASOCKET_ADDRMIN’
   89 |                 lua_pushlstring(L, addr_data, LUASOCKET_ADDRMIN(addr));
      |                                               ^~~~~~~~~~~~~~~~~
make[2]: *** [/usr/src/linux-headers-6.1.0-21-common/scripts/Makefile.build:255: /opt/lunatik/lib/luasocket.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.1.0-21-common/Makefile:2035: /opt/lunatik] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-21-arm64'
make: *** [Makefile:14: all] Error 2
```

**Comment by lneto** [comment]
that's weird.. do you know if is your kernel patched?

`addr->sa_data` is supposed to be `char[14]` not `char[]`, as in:

https://elixir.bootlin.com/linux/v6.1/source/include/linux/socket.h#L36

can you take a look at the source your kernel was built with?

**Comment by jperon** [comment]
It’s differs here: corresponding lines `/usr/src/linux-headers-6.1.0-22-common/include/linux/socket.h` in are:

```c
struct sockaddr {
        sa_family_t     sa_family;      /* address family, AF_xxx       */
        union {
                char sa_data_min[14];           /* Minimum 14 bytes of protocol address */
                DECLARE_FLEX_ARRAY(char, sa_data);
        };
};
```

Not a blocker for me, as I could install kernel 6.9 from backports, but I guess Debian Bookworm users on such platforms (nanopi R5S for me) could have the same problem.

**Comment by lneto** [comment]
I believe that if you use the following define instead of the one suited for  `< 6.2`, it would work..

https://github.com/luainkernel/lunatik/blob/master/lib/luasocket.c#L45

however, I'm not sure how to identify this Debian patch in our `#ifdef`s.. do you know if there's such thing as `DEBIAN` definition? we could check for such macro..

**Comment by jperon** [comment]
The change seems to have been introduced in kernel v. 6.1.80:
https://elixir.bootlin.com/linux/v6.1.80/source/include/linux/socket.h#L36

The kernel version referenced by `linux-headers-6.1.0-22-common` under Debian is 6.1.94.

**Comment by lneto** [comment]
ah.. it looked like it was kernel v6.1.0.. so, all we need is to change this [line](https://github.com/luainkernel/lunatik/blob/master/lib/luasocket.c#L44) to 6.1.80 then.. that's it:

```
- #if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 2, 0)
+ #if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 1, 80)
```

can you try this and submit a patch if it works?

**Comment by jperon** [comment]
Just tested and it works.
