### ISSUE TITLE
Script to automatically install Lunatik on Debian update

### ISSUE THREAD

**Issue by jperon** [luainkernel/lunatik#195]
[Here is](https://gist.github.com/jperon/46f17707425b87ec6ed1dc56724e3cd8) a script that, in `/etc/kernel/postinst.d/`, installs Lunatik for the new kernel. Would it be worth a PR? If so, where should I put the script?

**Comment by lneto** [comment]
Hey, the link is not available for me (404); but I think it is worth anyway =).. perhaps `tools/`?

**Comment by jperon** [comment]
Sorry, I hadn’t added `https://` at the beginning of the link…
