### ISSUE TITLE
the compilation is broken

### ISSUE THREAD

**Issue by sav** [luainkernel/lunatik#205]
```
$ make
make -C /lib/modules//build M=/home/sav/l2 CONFIG_LUNATIK=m	\
CONFIG_LUNATIK_RUN=m CONFIG_LUNATIK_RUNTIME=y CONFIG_LUNATIK_DEVICE=m	\
CONFIG_LUNATIK_LINUX=m CONFIG_LUNATIK_NOTIFIER=m CONFIG_LUNATIK_SOCKET=m \
CONFIG_LUNATIK_RCU=m CONFIG_LUNATIK_THREAD=m CONFIG_LUNATIK_FIB=m \
CONFIG_LUNATIK_DATA=m CONFIG_LUNATIK_PROBE=m CONFIG_LUNATIK_SYSCALL=m \
CONFIG_LUNATIK_XDP=m CONFIG_LUNATIK_FIFO=m CONFIG_LUNATIK_XTABLE=m \
CONFIG_LUNATIK_NETFILTER=m CONFIG_LUNATIK_COMPLETION=m
make[1]: *** /lib/modules//build: No such file or directory.  Stop.
make: *** [Makefile:16: all] Error 2
```

it seems like the KERNEL_VERSION variable is expected but is undefined.

**Comment by sav** [comment]
@jperon I think this may have to do with your recent changes, not sure what was the original intention so maybe if you could take a look, as well? thanks.

**Comment by jperon** [comment]
It certainly has to do with my changes, but what’s weird is that it should be defined by default thanks to this line: https://github.com/luainkernel/lunatik/blob/a56ed5e7c2da0c49491d28358ac5822336483709/Makefile#L4. Don’t you have `uname` on your system?

**Comment by sav** [comment]
> . Don’t you have `uname` on your system?

I do. 

https://github.com/luainkernel/lunatik/blob/master/Makefile#L5

The line below is still refering to KERNEL_VERSION though. I think you missed that.
