### ISSUE TITLE
What is the least supported version of kernel?

### ISSUE THREAD

**Issue by ziyao233** [luainkernel/lunatik#40]

**Comment by lneto** [comment]
Hi @ziyao233, I didn't test it, but I believe it must work at least with v4.9 (which is the one introduced `get_random_u32/64`). It's easy to adapt to the former random API though, if you need to run an older version.

**Comment by ziyao233** [comment]
Thanks for your comment. I have tried on Debian 11 (5.10) and found that `linux/stdarg.h` is missed. After create a link to gcc's implementation it built successfully but failed to load.

**Comment by lneto** [comment]
can you share the error message? I think a cleaner solution would be changing `include/stdard.h`:

```
#if LINUX_VERSION_CODE > KERNEL_VERSION(5,1,0)
#include <linux/stdarg.h>
#else
#include <stdarg.h>
#endif
```

**Comment by ziyao233** [comment]
Sorry that machine running Debian died this morning :(
The error message is `linux/stdarg.h not found` or something similar. I will try this modification later in a virtual machine.

**Comment by lneto** [comment]
thanks, @ziyao233! I meant the runtime error (it should appears on syslog, e.g., `sudo dmesg`). Please let me know if you try it again. I should make a new release soon.

**Comment by ziyao233** [comment]
> can you share the error message? I think a cleaner solution would be changing `include/stdard.h`:
> 
> ```
> #if LINUX_VERSION_CODE >= KERNEL_VERSION(5,15,0)
> #include <linux/stdarg.h>
> #else
> #include <stdarg.h>
> #endif
> ```

This is not a clear fix. Because stdarg.h is also in the `include` directory of this project, which is included in the search path and has a higher priority than gcc's `stdarg.h`. So `#include <stdarg.h>` actually includes `include/stdarg.h` , making no sense.

**Comment by ziyao233** [comment]
> thanks, @ziyao233! I meant the runtime error (it should appears on syslog, e.g., `sudo dmesg`). Please let me know if you try it again. I should make a new release soon.

I have tried again on Debian 11 (5.10 also).

```
lunatik: invalid option '%l' to 'lua_pushfstring'
insmod: Error: could not insert module lunatik_run.ko: Invalid parameters
```

**Comment by lneto** [comment]
> > can you share the error message? I think a cleaner solution would be changing `include/stdard.h`:
> > ```
> > #if LINUX_VERSION_CODE >= KERNEL_VERSION(5,15,0)
> > #include <linux/stdarg.h>
> > #else
> > #include <stdarg.h>
> > #endif
> > ```
> 
> This is not a clear fix. Because stdarg.h is also in the `include` directory of this project, which is included in the search path and has a higher priority than gcc's `stdarg.h`. So `#include <stdarg.h>` actually includes `include/stdarg.h` , making no sense.

you're absolutely right! Sorry for the noise. However, I think you can just remove this file (then the build will include the correct one).

**Comment by lneto** [comment]
> > thanks, @ziyao233! I meant the runtime error (it should appears on syslog, e.g., `sudo dmesg`). Please let me know if you try it again. I should make a new release soon.
> 
> I have tried again.
> 
> ```
> lunatik: invalid option '%l' to 'lua_pushfstring'
> insmod: Error: could not insert module lunatik_run.ko: Invalid parameters
> ```

can you please check the permissions of `/lib/modules/lua/lunatik.lua`?
```
$ ls -l /lib/modules/lua/lunatik.lua
-rw-r--r-- 1 root root 1615 May 13 22:06 /lib/modules/lua/lunatik.lua
```
does it looks like this?

BTW, thanks for the report, I just found an error on error handling:
https://github.com/luainkernel/lunatik/blob/v3.0/lunatik_aux.c#L42; it should respect https://www.lua.org/manual/5.4/manual.html#lua_pushfstring, that is, `%lld` is not allowed. I will fix this soon; however, it isn't the actual issue you have.

**Comment by lneto** [comment]
update: I've opened a PR with the error handling fix.. https://github.com/luainkernel/lunatik/pull/44

**Comment by ziyao233** [comment]
> does it looks like this?

Yes

**Comment by ziyao233** [comment]
> update: I've opened a PR with the error handling fix.. #44

I just pulled the last branch, built and try again. Now there is no message about `lua_pushfstring()`, but something like:

```
lunatik: kernel_read failure -22
```

(This is a section of kernel log)

At the same time, `lunatik_run.ko` failed to load still.

**Comment by lneto** [comment]
> > update: I've opened a PR with the error handling fix.. #44
> 
> I just pulled the last branch, built and try again. Now there is no message about `lua_pushfstring()`, but something like:
> 
> ```
> lunatik: kernel_read failure -22
> ```
> 
> (This is a section of kernel log)
> 
> At the same time, `lunatik_run.ko` failed to load still.

it looks like the `kernel_read` API has changed.. can you share your actual kernel version?

**Comment by ziyao233** [comment]
> it looks like the `kernel_read` API has changed.. can you share your actual kernel version?

```
Linux debian 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
```

**Comment by lneto** [comment]
> > it looks like the `kernel_read` API has changed.. can you share your actual kernel version?
> 
> ```
> Linux debian 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
> ```

I'm running `5.19.0` and it doesn't seem to have any difference from `5.10.0` regarding `kernel_read`. My educated guess is that it's returning `-22 (-EINVAL)` due to file permissions. Could you try to enforce permissions?

```
chmod 0755 /lib/modules/lua
chmod 0644 /lib/modules/lua/lunatik.lua
```

Also, could you try the following on master?

```
make
sudo make install
sudo lunatik
```
